### ISSUE TITLE
无法下载歌曲

### ISSUE THREAD

**Issue by ququ2014** [QiuChenlyOpenSource/QQFlacMusicDownloader#108]
2023-08-04 15:14:45 WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
2023-08-04 15:14:45  * Running on all addresses (0.0.0.0)
2023-08-04 15:14:45  * Running on http://127.0.0.1:8899
2023-08-04 15:14:45  * Running on http://172.17.0.3:8899
2023-08-04 15:14:45 Press CTRL+C to quit
2023-08-04 15:15:02 172.17.0.1 - - [04/Aug/2023 07:15:02] "GET / HTTP/1.1" 302 -
2023-08-04 15:15:02 172.17.0.1 - - [04/Aug/2023 07:15:02] "GET /index.html HTTP/1.1" 304 -
2023-08-04 15:15:02 172.17.0.1 - - [04/Aug/2023 07:15:02] "GET /assets/index-1d4497e6.js HTTP/1.1" 304 -
2023-08-04 15:15:02 172.17.0.1 - - [04/Aug/2023 07:15:02] "GET /assets/index-77d4dafe.css HTTP/1.1" 304 -
2023-08-04 15:15:02 172.17.0.1 - - [04/Aug/2023 07:15:02] "GET /getConfig HTTP/1.1" 200 -
2023-08-04 15:15:05 172.17.0.1 - - [04/Aug/2023 07:15:05] "GET /getConfig HTTP/1.1" 200 -
2023-08-04 15:15:16 172.17.0.1 - - [04/Aug/2023 07:15:16] "GET /qq/search/小城大事/1/30 HTTP/1.1" 200 -
2023-08-04 15:15:24 172.17.0.1 - - [04/Aug/2023 07:15:24] "POST /download HTTP/1.1" 200 -
2023-08-04 15:14:45 kw_token已生成 cdb524f42f0ce19b169b8072123a4727=hBYKKdfZDtQiXf8bbGszGxnj78eSdPTb
2023-08-04 15:14:45  * Serving Flask app 'flaskSystem.App'
2023-08-04 15:14:45  * Debug mode: off
2023-08-04 15:17:19 172.17.0.1 - - [04/Aug/2023 07:17:19] "GET /wyy/search/小城大事/1/30 HTTP/1.1" 200 -
2023-08-04 15:17:27 172.17.0.1 - - [04/Aug/2023 07:17:27] "POST /download HTTP/1.1" 200 -
2023-08-04 15:17:28 exception calling callback for <Future at 0x7f3a28918bb0 state=finished raised JSONDecodeError>
2023-08-04 15:17:28 Traceback (most recent call last):
2023-08-04 15:17:28   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 971, in json
2023-08-04 15:17:28     return complexjson.loads(self.text, **kwargs)
2023-08-04 15:17:28   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
2023-08-04 15:17:28     return _default_decoder.decode(s)
2023-08-04 15:17:28   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
2023-08-04 15:17:28     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2023-08-04 15:17:28   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
2023-08-04 15:17:28     raise JSONDecodeError("Expecting value", s, err.value) from None
2023-08-04 15:17:28 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-08-04 15:17:28 
2023-08-04 15:17:28 During handling of the above exception, another exception occurred:
2023-08-04 15:17:28 
2023-08-04 15:17:28 Traceback (most recent call last):
2023-08-04 15:17:28   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 330, in _invoke_callbacks
2023-08-04 15:17:28     callback(self)
2023-08-04 15:17:28   File "/workspace/flaskSystem/App.py", line 85, in done
2023-08-04 15:17:28     ret = ret.result()
2023-08-04 15:17:28   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
2023-08-04 15:17:28     return self.__get_result()
2023-08-04 15:17:28   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
2023-08-04 15:17:28     raise self._exception
2023-08-04 15:17:28   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
2023-08-04 15:17:28     result = self.fn(*self.args, **self.kwargs)
2023-08-04 15:17:28   File "/workspace/flaskSystem/src/Common/Tools.py", line 157, in downSingle
2023-08-04 15:17:28     link: str = handleWyy(music['mid'])
2023-08-04 15:17:28   File "/workspace/flaskSystem/src/Common/Tools.py", line 99, in handleWyy
2023-08-04 15:17:28     url = netes.getMusicUrl(mid)
2023-08-04 15:17:28   File "/workspace/flaskSystem/src/Api/Netease.py", line 286, in getMusicUrl
2023-08-04 15:17:28     r = r.json()
2023-08-04 15:17:28   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 975, in json
2023-08-04 15:17:28     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
2023-08-04 15:17:28 requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-08-04 15:17:55 172.17.0.1 - - [04/Aug/2023 07:17:55] "GET /qq/search/小城大事/1/30 HTTP/1.1" 200 -
2023-08-04 15:18:03 172.17.0.1 - - [04/Aug/2023 07:18:03] "GET /qq/search/用手走路/1/30 HTTP/1.1" 200 -
2023-08-04 15:18:09 172.17.0.1 - - [04/Aug/2023 07:18:09] "POST /download HTTP/1.1" 200 -

**Comment by QiuChenly** [comment]
QQ的搜索结果怎么是网易云接口在下载？

**Comment by ququ2014** [comment]
qq点过一次下载没反应，就切了网易云点下载，也是不行

**Comment by QiuChenly** [comment]
网易云接口早挂了 不看说明吗
Qq我这都是正常的 你不行找找自己原因 日志也不给全 我靠猜吗？你这日志还是网易云的 找找自己原因吧😅
