### ISSUE TITLE
下载不了？原来是这个问题🤣🤣

### ISSUE THREAD

**Issue by txxxtxx** [QiuChenlyOpenSource/QQFlacMusicDownloader#112]
为什么我的下载不了啊？

2023-08-09 15:33:44 准备开始下载任务
2023-08-09 15:33:44 172.17.0.1 - - [09/Aug/2023 07:33:44] "POST /download HTTP/1.1" 200 -
2023-08-09 15:33:46 exception calling callback for <Future at 0x7f439e299520 state=finished raised JSONDecodeError>
2023-08-09 15:33:46 Traceback (most recent call last):
2023-08-09 15:33:46   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 971, in json
2023-08-09 15:33:46     return complexjson.loads(self.text, **kwargs)
2023-08-09 15:33:46   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
2023-08-09 15:33:46     return _default_decoder.decode(s)
2023-08-09 15:33:46   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
2023-08-09 15:33:46     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2023-08-09 15:33:46   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
2023-08-09 15:33:46     raise JSONDecodeError("Expecting value", s, err.value) from None
2023-08-09 15:33:46 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-08-09 15:33:46 
2023-08-09 15:33:46 During handling of the above exception, another exception occurred:
2023-08-09 15:33:46 
2023-08-09 15:33:46 Traceback (most recent call last):
2023-08-09 15:33:46   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 330, in _invoke_callbacks
2023-08-09 15:33:46     callback(self)
2023-08-09 15:33:46   File "/workspace/flaskSystem/App.py", line 85, in done
2023-08-09 15:33:46     ret = ret.result()
2023-08-09 15:33:46   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
2023-08-09 15:33:46     return self.__get_result()
2023-08-09 15:33:46   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
2023-08-09 15:33:46     raise self._exception
2023-08-09 15:33:46   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
2023-08-09 15:33:46     result = self.fn(*self.args, **self.kwargs)
2023-08-09 15:33:46   File "/workspace/flaskSystem/src/Common/Tools.py", line 157, in downSingle
2023-08-09 15:33:46     link: str = handleWyy(music['mid'])
2023-08-09 15:33:46   File "/workspace/flaskSystem/src/Common/Tools.py", line 99, in handleWyy
2023-08-09 15:33:46     url = netes.getMusicUrl(mid)
2023-08-09 15:33:46   File "/workspace/flaskSystem/src/Api/Netease.py", line 286, in getMusicUrl
2023-08-09 15:33:46     r = r.json()
2023-08-09 15:33:46   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 975, in json
2023-08-09 15:33:46     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
2023-08-09 15:33:46 requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by QiuChenly** [comment]
网易云早tm挂了 不看说明是吧？
