### ISSUE TITLE
运行python MainServer.py报错

### ISSUE THREAD

**Issue by impersonal-byte** [QiuChenlyOpenSource/QQFlacMusicDownloader#115]
PS G:\Software installation\MusicD\QQFlacMusicDownloader-master> python MainServer.py
Traceback (most recent call last):
  File "G:\Software installation\MusicD\QQFlacMusicDownloader-master\MainServer.py", line 16, in <module>
    from flaskSystem.App import Start  # 必须先加载他 这是初始化flask框架代码
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Software installation\MusicD\QQFlacMusicDownloader-master\flaskSystem\App.py", line 83, in <module>
    c = Downloader()
        ^^^^^^^^^^^^
  File "G:\Software installation\MusicD\QQFlacMusicDownloader-master\flaskSystem\src\Common\Concurrency.py", line 18, in __init__
    self.set_folder(os.getcwd() + '/music/')
  File "G:\Software installation\MusicD\QQFlacMusicDownloader-master\flaskSystem\src\Common\Concurrency.py", line 26, in set_folder
    os.mkdir(self.folder)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'G:\\Softwareinstallation\\MusicD\\QQFlacMusicDownloader-master/music/'
Widows 11 22H2 内部版本23521.100
python  3.11.2

**Comment by impersonal-byte** [comment]
两周前有一个类似issue，但是我没有找到config.cfg文件

**Comment by QiuChenly** [comment]
重新拉取代码。你这个代码早他妈N年前就修复了。
