### ISSUE TITLE
下载报错

### ISSUE THREAD

**Issue by BIGMONK** [QiuChenlyOpenSource/QQFlacMusicDownloader#130]
错误日志：
准备开始下载任务
192.168.31.103 - - [01/Sep/2023 11:09:49] "POST /download HTTP/1.1" 200 -
exception calling callback for <Future at 0x7286cfb6a0 state=finished raised KeyError>
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/home/QQFlacMusicDownloader/flaskSystem/App.py", line 99, in done
    ret = ret.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/QQFlacMusicDownloader/flaskSystem/src/Common/Tools.py", line 188, in downSingle
    super_music_info = handleMigu(music['mid'], music['prefix'])
  File "/home/QQFlacMusicDownloader/flaskSystem/src/Common/Tools.py", line 96, in handleMigu
    url = mg.getDownloadLink(mid, _type)
  File "/home/QQFlacMusicDownloader/flaskSystem/src/Api/MiGu.py", line 159, in getDownloadLink
    url = music['androidUrl']
KeyError: 'androidUrl'

**Comment by shunia** [comment]
同上，应该是下载的源站挂了，不知道有没有修复的可能。

**Comment by QiuChenly** [comment]
migu已经挂了。
