### ISSUE TITLE
写入元数据出错

### ISSUE THREAD

**Issue by KaiHuaDou** [QiuChenlyOpenSource/QQFlacMusicDownloader#133]
```log
准备开始下载任务
192.168.3.5 - - [06/Sep/2023 22:02:33] "POST /download HTTP/1.1" 200 -
正在下载 | ラヴ (LOVE) / ピノキオピー (匹诺曹P) - ねぇねぇねぇ。 (呐呐呐。) [无损品质 FLAC] 25.63MB - F000003B3G893DsnLC.flac
ラヴ (LOVE) ピノキオピー (匹诺曹P) ねぇねぇねぇ。 (呐呐呐。) 316613809 成功使用MusicID精确匹配到了QQ曲库信息。
exception calling callback for <Future at 0x1b288c712a0 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\server\python310\lib\concurrent\futures\_base.py", line 342, in _invoke_callbacks
    callback(self)
  File "D:\server\flacMusic\flaskSystem\App.py", line 99, in done
    ret = ret.result()
  File "D:\server\python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "D:\server\python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "D:\server\python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\server\flacMusic\flaskSystem\src\Common\Tools.py", line 289, in downSingle
    fulfillMusicMetaData(localFile, super_music_info)
  File "D:\server\flacMusic\flaskSystem\src\Common\Tools.py", line 517, in fulfillMusicMetaData
    gener.append(it['name'])
TypeError: string indices must be integers
```

实际运行结果是元数据写入失败，歌曲文件是正常的。

**Comment by QiuChenly** [comment]
统一回复：此问题是因为上周合并了另一个人提交的pull引起的错误，今天会修复。

**Comment by QiuChenly** [comment]
由于合并了一个第三方开发者包含低级逻辑错误的代码pull引起的错误，现已修正。
参见：https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/commit/972a78a9522853b237255e9715b34d93c7367dee
