### ISSUE TITLE
大佬，下载出错啦

### ISSUE THREAD

**Issue by kkgoodBoy** [QiuChenlyOpenSource/QQFlacMusicDownloader#134]
准备开始下载任务
127.0.0.1 - - [07/Sep/2023 08:26:04] "POST /download HTTP/1.1" 200 -
正在下载 | 爱情的尽头 / 伍佰 & China Blue - 挪威的森林 [无损品质 FLAC] 42.98MB - F000004PzYqj3GbAH2.flac
爱情的尽头 伍佰 & China Blue 挪威的森林 4928821 成功使用MusicID精确匹配到了QQ曲库信息。
exception calling callback for <Future at 0x1f472653910 state=finished raised TypeError>
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "F:\QQFlacMusicDownloader-main\flaskSystem\App.py", line 99, in done
    ret = ret.result()
          ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Program Files\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\QQFlacMusicDownloader-main\flaskSystem\src\Common\Tools.py", line 289, in downSingle
    fulfillMusicMetaData(localFile, super_music_info)
  File "F:\QQFlacMusicDownloader-main\flaskSystem\src\Common\Tools.py", line 517, in fulfillMusicMetaData
    gener.append(it['name'])
                 ~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
WebSocket transport not available. Install simple-websocket for improved performance.
Traceback (most recent call last):
  File "F:\QQFlacMusicDownloader-main\MainServer.py", line 27, in <module>
    Start(args.port)  # 最后启动总函数
    ^^^^^^^^^^^^^^^^
  File "F:\QQFlacMusicDownloader-main\flaskSystem\App.py", line 165, in Start
    socketio.run(app, host='0.0.0.0', port=port)
  File "F:\QQFlacMusicDownloader-main\venv\Lib\site-packages\flask_socketio\__init__.py", line 640, in run
    raise RuntimeError('The Werkzeug web server is not '
RuntimeError: The Werkzeug web server is not designed to run in production. Pass allow_unsafe_werkzeug=True to the run() method to disable this error.

**Comment by QiuChenly** [comment]
统一回复：此问题是因为上周合并了另一个人提交的issues引起的错误，今天会修复。

**Comment by QiuChenly** [comment]
由于合并了一个第三方开发者包含低级逻辑错误的代码pull引起的错误，现已修正。
参见：https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/commit/972a78a9522853b237255e9715b34d93c7367dee
