### ISSUE TITLE
网易云音乐下载出现如下提示，不知道是什么原因？谢谢

### ISSUE THREAD

**Issue by surenet** [QiuChenlyOpenSource/QQFlacMusicDownloader#137]
127.0.0.1 - - [08/Sep/2023 23:34:25] "POST /download HTTP/1.1" 200 -
exception calling callback for <Future at 0x1ff8f3e46d0 state=finished raised JSONDecodeError>
Traceback (most recent call last):
  File "D:\python\QQFlacMusicDownloader\venv\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "D:\python\QQFlacMusicDownloader\flaskSystem\App.py", line 99, in done
    ret = ret.result()
          ^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\QQFlacMusicDownloader\flaskSystem\src\Common\Tools.py", line 197, in downSingle
    link: str = handleWyy(music['mid'])
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\QQFlacMusicDownloader\flaskSystem\src\Common\Tools.py", line 104, in handleWyy
    url = netes.getMusicUrl(mid)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\QQFlacMusicDownloader\flaskSystem\src\Api\Netease.py", line 286, in getMusicUrl
    r = r.json()
        ^^^^^^^^
  File "D:\python\QQFlacMusicDownloader\venv\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by surenet** [comment]
QQ音乐下载，有下面提示
127.0.0.1 - - [08/Sep/2023 23:37:19] "POST /download HTTP/1.1" 200 -
正在下载 | 山歌寥哉 / 刀郎 - 花妖 [无损品质 FLAC] 55.47MB - F000000E55jQ1SpzEI.flac
山歌寥哉 刀郎 花妖 422770732 成功使用MusicID精确匹配到了QQ曲库信息。
exception calling callback for <Future at 0x1ff8f3c7a50 state=finished raised TypeError>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "D:\python\QQFlacMusicDownloader\flaskSystem\App.py", line 99, in done
    ret = ret.result()
          ^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\QQFlacMusicDownloader\flaskSystem\src\Common\Tools.py", line 289, in downSingle
    fulfillMusicMetaData(localFile, super_music_info)
  File "D:\python\QQFlacMusicDownloader\flaskSystem\src\Common\Tools.py", line 517, in fulfillMusicMetaData
    gener.append(it['name'])
                 ~~^^^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by QiuChenly** [comment]
1. 你但凡看完了readme 都问不出来为什么网易云下不了歌：早给你打上x了告诉你接口已经挂了自己不看就在这问 要不是我今天心情不坏早喷你了。
2. 由于某一周合并了一个第三方作者的代码导致qq音乐的元数据填充算法出现了一个低级语法错误，现已修正。参见：https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/commit/972a78a9522853b237255e9715b34d93c7367dee
