### ISSUE TITLE
网易云音乐下载出现下面问题，是没登录的原因吗？

### ISSUE THREAD

**Issue by surenet** [QiuChenlyOpenSource/QQFlacMusicDownloader#138]
127.0.0.1 - - [09/Sep/2023 10:24:27] "GET /wyy/search/童安格/1/30 HTTP/1.1" 200 -
准备开始下载任务
127.0.0.1 - - [09/Sep/2023 10:24:34] "POST /download HTTP/1.1" 200 -
exception calling callback for <Future at 0x1369cee6290 state=finished raised JSONDecodeError>
Traceback (most recent call last):
  File "D:\python\QQFlacMusicDownloader\venv\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "D:\python\QQFlacMusicDownloader\flaskSystem\App.py", line 99, in done
    ret = ret.result()
          ^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\QQFlacMusicDownloader\flaskSystem\src\Common\Tools.py", line 197, in downSingle
    link: str = handleWyy(music['mid'])
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\QQFlacMusicDownloader\flaskSystem\src\Common\Tools.py", line 104, in handleWyy
    url = netes.getMusicUrl(mid)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\QQFlacMusicDownloader\flaskSystem\src\Api\Netease.py", line 286, in getMusicUrl
    r = r.json()
        ^^^^^^^^
  File "D:\python\QQFlacMusicDownloader\venv\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by QiuChenly** [comment]
是接口挂了....哥们看下readme表格

**Comment by Theearthquake** [comment]
> 是接口挂了....哥们看下readme表格

老哥，那这种情况是更换python端口吗，我也遇到这种情况
