### ISSUE TITLE
网易云下载没有反应,Mac Studio macOS14.0beta python3.10

### ISSUE THREAD

**Issue by yuanyiming** [QiuChenlyOpenSource/QQFlacMusicDownloader#140]
这是我运行时的全部过程,点了下载,但是文件夹里什么都没有
Last login: Sat Sep  9 21:38:35 on ttys000
yuanyiming@belugadeMac-Studio ~ % cd /Users/yuanyiming/Downloads/QQFlacMusicDownloader-master
yuanyiming@belugadeMac-Studio QQFlacMusicDownloader-master % python3 MainServer.py
kw_token已生成 cdb524f42f0cer9b268e4v7y734w5esq24=yXJ7b8wTC578sjh6ZQ3f8i4YtwEzQXiD
 * Serving Flask app 'flaskSystem.App'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8899
 * Running on http://192.168.100.223:8899
Press CTRL+C to quit
127.0.0.1 - - [09/Sep/2023 21:46:34] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [09/Sep/2023 21:46:34] "GET /index.html HTTP/1.1" 304 -
127.0.0.1 - - [09/Sep/2023 21:46:34] "GET /assets/index-6e13df5b.css HTTP/1.1" 304 -
127.0.0.1 - - [09/Sep/2023 21:46:34] "GET /assets/index-5e6f3a3e.js HTTP/1.1" 304 -
127.0.0.1 - - [09/Sep/2023 21:46:34] "GET /getConfig HTTP/1.1" 200 -
127.0.0.1 - - [09/Sep/2023 21:46:46] "GET /wyy/search/在这个世界相遇/1/30 HTTP/1.1" 200 -
准备开始下载任务
127.0.0.1 - - [09/Sep/2023 21:46:52] "POST /download HTTP/1.1" 200 -
exception calling callback for <Future at 0x1031c53f0 state=finished raised JSONDecodeError>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/yuanyiming/Downloads/QQFlacMusicDownloader-master/flaskSystem/App.py", line 99, in done
    ret = ret.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/yuanyiming/Downloads/QQFlacMusicDownloader-master/flaskSystem/src/Common/Tools.py", line 197, in downSingle
    link: str = handleWyy(music['mid'])
  File "/Users/yuanyiming/Downloads/QQFlacMusicDownloader-master/flaskSystem/src/Common/Tools.py", line 104, in handleWyy
    url = netes.getMusicUrl(mid)
  File "/Users/yuanyiming/Downloads/QQFlacMusicDownloader-master/flaskSystem/src/Api/Netease.py", line 286, in getMusicUrl
    r = r.json()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yuanyiming** [comment]
接口挂了?

**Comment by yuanyiming** [comment]
哦看了readme.md了

**Comment by yuanyiming** [comment]
喔,QQ音乐弄好了
