### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by GavinLiu666** [QiuChenlyOpenSource/QQFlacMusicDownloader#72]
exception calling callback for <Future at 0x7f5600acb6a0 state=finished raised OSError>
Traceback (most recent call last):
  File "/home/lyle/miniconda3/envs/music/lib/python3.10/concurrent/futures/_base.py", line 342, in _invoke_callbacks
    callback(self)
  File "/opt/QQFlacMusicDownloader/flaskSystem/App.py", line 85, in done
    ret = ret.result()
  File "/home/lyle/miniconda3/envs/music/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/lyle/miniconda3/envs/music/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/lyle/miniconda3/envs/music/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/QQFlacMusicDownloader/flaskSystem/src/Common/Tools.py", line 256, in downSingle
    with open(localFile, 'wb') as code:
OSError: [Errno 36] File name too long: '/xxxxxx/Wiener Philharmoniker/Wiener Philharmoniker - Symphony No. 9 in D Minor, WAB 109 - Edition： Leopold Nowak - Bruckner： Symphony No. 9 in D Minor, WAB 109 - Edition： Leopold Nowak - III. Adagio. Langsam, feierlich (D小调第9号交响曲 - 第三乐章 柔板，非常缓慢，庄严的) (Live).mp3'

**Comment by QiuChenly** [comment]
卧槽，这也长了吧

**Comment by GavinLiu666** [comment]
能不能截一下

**Comment by ames0k0** [comment]
Can you leave a link to this music (resource) ?
-- Looks like a 3 different music, no ?!
