### ISSUE TITLE
网易云音乐下载失败

### ISSUE THREAD

**Issue by MoTingFeng** [QiuChenlyOpenSource/QQFlacMusicDownloader#74]
所有的网易云音乐都下载失败，qq音乐等下载正常
以下是命令行中的报错信息
~~~
准备开始下载任务
127.0.0.1 - - [14/Jun/2023 14:29:12] "POST /download HTTP/1.1" 200 -
exception calling callback for <Future at 0x1f20b8f6110 state=finished raised JSONDecodeError>
Traceback (most recent call last):
  File "D:\0001\Python\Python3.11.2\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0001\Python\Python3.11.2\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0001\Python\Python3.11.2\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0001\Python\Python3.11.2\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\0001\Python\Python3.11.2\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "E:\RuanJian\Music\music-downlader\QQFlacMusicDownloader-main\flaskSystem\App.py", line 85, in done
    ret = ret.result()
          ^^^^^^^^^^^^
  File "D:\0001\Python\Python3.11.2\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "D:\0001\Python\Python3.11.2\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\0001\Python\Python3.11.2\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\RuanJian\Music\music-downlader\QQFlacMusicDownloader-main\flaskSystem\src\Common\Tools.py", line 157, in downSingle
    link: str = handleWyy(music['mid'])
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\RuanJian\Music\music-downlader\QQFlacMusicDownloader-main\flaskSystem\src\Common\Tools.py", line 99, in handleWyy
    url = netes.getMusicUrl(mid)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\RuanJian\Music\music-downlader\QQFlacMusicDownloader-main\flaskSystem\src\Api\Netease.py", line 286, in getMusicUrl
    r = r.json()
        ^^^^^^^^
  File "D:\0001\Python\Python3.11.2\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by QiuChenly** [comment]
因为第三方服务器已经挂掉了  不是通过你的ck下载的

**Comment by MoTingFeng** [comment]
> 因为第三方服务器已经挂掉了 不是通过你的ck下载的

好吧，多谢大佬了
