### ISSUE TITLE
kw接口时效

### ISSUE THREAD

**Issue by luzking** [QiuChenlyOpenSource/QQFlacMusicDownloader#82]
报错信息：
Traceback (most recent call last):
  File "/mnt/d/linux_soft/QQFlacMusicDownloader-main/MainServer.py", line 18, in <module>
    from flaskSystem.API.kw import init as kw  # 下面无需顺序
  File "/mnt/d/linux_soft/QQFlacMusicDownloader-main/flaskSystem/API/kw.py", line 14, in <module>
    kw = KwApi()
解决方法：注释掉kw相关代码
#from flaskSystem.API.kw import init as kw  # 下面无需顺序
#kw()

**Comment by luzking** [comment]
ConnectionResetError: [Errno 104] Connection reset by peer
其他接口也时效了

**Comment by QiuChenly** [comment]
酷我接口没有失效，刚才测试正常下载。

**Comment by luzking** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我已经收到了您的邮件。我会在短期时间内尽快给你回复。
