### ISSUE TITLE
163的歌曲无法下载

### ISSUE THREAD

**Issue by zed268** [QiuChenlyOpenSource/QQFlacMusicDownloader#88]
## 问题表现
无论是登录163账号从喜欢的音乐中下载，还是搜索163中的歌曲进行下载，歌曲信息部分可正常显示，部分歌曲无法解析时间信息(显示为1970-01-01)。点击下载时，终端会报错。无论是Mac OS还是Windows都是同样的问题。

前端网页中的错误如下图：
![2.PNG](https://s2.loli.net/2023/07/18/1HFGJZRwrENzMX3.png)

## 终端报错内容 (以Windows环境为例，点击下载前的终端日志内容已去除)
准备开始下载任务
127.0.0.1 - - [18/Jul/2023 14:09:43] "POST /download HTTP/1.1" 200 -
exception calling callback for <Future at 0x7ecd2d0 state=finished raised JSONDecodeError>
Traceback (most recent call last):
  File "C:\Users\zed\AppData\Roaming\Python\Python311\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "d:\QQFlacMusicDownloader-main\flaskSystem\App.py", line 85, in done
    ret = ret.result()
          ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Program Files\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\QQFlacMusicDownloader-main\flaskSystem\src\Common\Tools.py", line 157, in downSingle
    link: str = handleWyy(music['mid'])
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\QQFlacMusicDownloader-main\flaskSystem\src\Common\Tools.py", line 99, in handleWyy
    url = netes.getMusicUrl(mid)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\QQFlacMusicDownloader-main\flaskSystem\src\Api\Netease.py", line 286, in getMusicUrl
    r = r.json()
        ^^^^^^^^
  File "C:\Users\zed\AppData\Roaming\Python\Python311\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Windows
硬件环境：ThinkPad T450s (Intel Core i7 5600U，12GB RAM)
操作系统：Windows Server 2008 R2 Enterprise SP1 (当作64位的Win7就好)
Python版本号：3.11.2 (由于官方版从3.9开始不支持Win NT 6.1，故使用魔改版：[adang1345/PythonWin7](https://github.com/adang1345/PythonWin7))

### Mac OS
虚拟机管理程序：VMware Workstation 17.0.0 Pro
虚拟机配置：Workstation 16.2.x，4个逻辑CPU(物理CPU：Intel Core i7 8565U)，10GB RAM
操作系统版本：11.2.3
Python版本号：3.9.13

**Comment by zed268** [comment]
刚看到历史问题，貌似暂时无解，先按未处理关闭了。抱歉，打扰了……
