### ISSUE TITLE
刚刚重新下载了新的QQFlacMusicDownloader出错

### ISSUE THREAD

**Issue by djapple** [QiuChenlyOpenSource/QQFlacMusicDownloader#98]
yy.feng@192 QQmusic-Down % python3 mainserver.py
Traceback (most recent call last):
  File "/Users/yy.feng/Desktop/QQmusic-Down/mainserver.py", line 16, in <module>
    from flaskSystem.App import Start  # 必须先加载他 这是初始化flask框架代码
  File "/Users/yy.feng/Desktop/QQmusic-Down/flaskSystem/App.py", line 87, in <module>
    c.set_folder(cfg['download_locate'])
  File "/Users/yy.feng/Desktop/QQmusic-Down/flaskSystem/src/Common/Concurrency.py", line 26, in set_folder
    os.mkdir(self.folder)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/Disk1/music/'
yy.feng@192 QQmusic-Down % 

MacOS 13.5
Python 3.9.6

**Comment by QiuChenly** [comment]
有一个配置文件忘了初始化检查目录是否存在了，自己删掉config.cfg文件即可

**Comment by StrollStars** [comment]
@QiuChenly 删掉后报错如下：
```
Traceback (most recent call last):
  File ",\QQFlacMusicDownloader\MainServer.py", line 18, in <module>
    from flaskSystem.API.kw import init as kw  # 下面无需顺序
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ",\QQFlacMusicDownloader\flaskSystem\API\kw.py", line 9, in <module>
    from flaskSystem.src.Api.Kuwo import KwApi
  File ",\QQFlacMusicDownloader\flaskSystem\src\Api\Kuwo.py", line 14, in <module>
    from flaskSystem.src.Common.Tools import subString
  File ",\QQFlacMusicDownloader\flaskSystem\src\Common\Tools.py", line 18, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

**Comment by QiuChenly** [comment]
重新拉取并使用requirements.txt重建环境。
